# Generated by Django 3.2.14 on 2022-11-16 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0021_auto_20221020_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Head Office | Building 259, 2nd Sector, North 90th St. New Cairo, Cairo - Egypt.', max_length=100)),
                ('phone', models.CharField(default='Phone . contact@example.com', max_length=50)),
                ('email', models.CharField(default='Email . +54 356 945234', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
