# Generated by Django 3.2.14 on 2022-11-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0023_auto_20221116_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name2',
        ),
    ]
