# Generated by Django 3.2.14 on 2022-11-19 13:46

from django.db import migrations, models
import django.db.models.deletion
import houses.models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0024_remove_about_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team_leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='about',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=houses.models.get_default_my_code, max_length=50)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('members', models.ManyToManyField(blank=True, null=True, to='houses.Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.team')),
            ],
        ),
    ]
