# Generated by Django 3.2.14 on 2022-11-20 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0025_auto_20221119_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='codes',
            field=models.ManyToManyField(blank=True, null=True, to='houses.Code'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
