# Generated by Django 3.2.14 on 2022-11-20 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0026_auto_20221120_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_leader',
            name='codes',
            field=models.ManyToManyField(blank=True, null=True, to='houses.Code'),
        ),
        migrations.AddField(
            model_name='team_leader',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, to='houses.Member'),
        ),
        migrations.AddField(
            model_name='team_leader',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
