# Generated by Django 3.2.14 on 2022-11-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0028_auto_20221121_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.code')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.team_leader')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.member')),
            ],
        ),
    ]
