# Generated by Django 3.2.14 on 2022-11-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0029_codepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepermission',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.team_leader'),
        ),
    ]
