# Generated by Django 3.2.14 on 2022-11-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0030_alter_codepermission_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.project'),
        ),
    ]
