# Generated by Django 3.2.14 on 2022-11-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0033_alter_member_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_leader',
            name='team_members',
        ),
    ]
