# Generated by Django 3.2.14 on 2022-11-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0034_remove_team_leader_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.team_leader'),
        ),
    ]
