# Generated by Django 3.2.14 on 2022-11-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0035_alter_member_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='team',
        ),
    ]
