# Generated by Django 3.2.14 on 2022-11-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0025_auto_20221116_1920'),
        ('houses', '0036_remove_code_team'),
    ]

    operations = [
    ]
