# Generated by Django 3.2.14 on 2022-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0038_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Ain Shokana', max_length=100),
        ),
    ]
