# Generated by Django 3.2.14 on 2022-11-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0041_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.location'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='location_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.location'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.location'),
        ),
    ]
